### ISSUE TITLE
针对php中数组的判断存在不足

### ISSUE THREAD

**Issue by Sndav** [LoRexxar/Kunlun-M#110]
![image](https://user-images.githubusercontent.com/10370671/98888971-fa3e0500-24d3-11eb-94a4-eac64874820d.png)
解析器认为这两个变量存在关联，但是事实上两个数组的键值不同，并没有关联关系

**Comment by LoRexxar** [comment]
这个问题之前就发现了，参考#93

**Comment by LoRexxar** [comment]
顺便问下，你这个魔改得还挺好的，能来个pr吗

**Comment by Sndav** [comment]
> 顺便问下，你这个魔改得还挺好的，能来个pr吗

安排！我把代码结构调整一下就pr

**Comment by LoRexxar** [comment]
记得发到dev啊

**Comment by Sndav** [comment]
> 记得发到dev啊

嗯嗯
