### ISSUE TITLE
Console模式是否可以提供一个简易的HTTP dashboard进行输出？

### ISSUE THREAD

**Issue by lazychanger** [LoRexxar/Kunlun-M#114]
我将 Kunlun-M 封装成了一个 docker 镜像。在docker镜像下使用console模式，对数据结果的采集成了一个问题
并且在docker镜像内，console模式的获取结果命令 check_log 会出现 Permission denied

![image](https://user-images.githubusercontent.com/20916944/100408210-5d6b9200-30a5-11eb-86fb-136168156d3d.png)

[docker hub]()
[git](https://github.com/lazychanger/docker-kunlun-mirror)

下列是我测试时候依次执行的命令：
````shell script
# 启动docker容器并且使用 kunlun console模式进行交互，-v 后参数为[扫描项目]:[容器内地址]
docker run -it -v /root/projects:/root/projects --rm kunlun-mirror:latest pyscan console

# 进入扫描模式
scan

# 设置扫描目录
scan target /root/projects

# 设置语言
scan language php

# 执行扫描
run

# 等待结束查看结果
check_log
````

- docker镜像内console模式进入结果状态，check_log权限问题
- 希望执行console模式时候，可以有一个简易的 http dashboard 提供结果内容

**Comment by lazychanger** [comment]
希望还可以提供一个类似 .gitignore 的项目忽略的配置文件

**Comment by LoRexxar** [comment]
http的可以考虑，我找时间弄一下

**Comment by LoRexxar** [comment]
.gitignore有的啊，能说下啥没忽略吗，我好像本地的都没啥问题

**Comment by lazychanger** [comment]
不是 .gitignore，是提供类似 .gitignore 的文件，描述忽略地址。防止浪费扫描

LoRexxar <notifications@github.com> 于2020年11月30日周一 上午10:09写道：

**Comment by LoRexxar** [comment]
噢，现在是通过黑名单目录实现的，我自己是够用了，如果有什么特殊情况需要，也可以大致描述一下

**Comment by lazychanger** [comment]
这种会更加灵活。
例如第三库就可以避免扫描、或者签名文件、已经压缩过的js。

.kunlunignore
```text
/vendor
/.idea
/static/js
/extension/qiniu-sdk
```

LoRexxar <notifications@github.com> 于2020年11月30日周一 下午2:00写道：

**Comment by LoRexxar** [comment]
可以考虑，我看看怎么做

**Comment by LoRexxar** [comment]
fixed in 2.1.0
