### ISSUE TITLE
未支持注释相关解析

### ISSUE THREAD

**Issue by p1g3** [LoRexxar/Kunlun-M#115]
对注释没有相关解析：
![image](https://user-images.githubusercontent.com/49426158/100472657-a3f9d480-3117-11eb-8bd0-8473eb814b17.png)

![image](https://user-images.githubusercontent.com/49426158/100472667-abb97900-3117-11eb-8016-f7b9ebbbd2bb.png)

还有之前在群里反应的报错没格式化的问题，我就不继续再这里另开一个issue了。

**Comment by LoRexxar** [comment]
看上去是一个设计原理的bug，我康康

**Comment by LoRexxar** [comment]
上面这一条报的是不确定的漏洞对吗

**Comment by p1g3** [comment]
是不确定的漏洞是什么意思？不太理解

**Comment by LoRexxar** [comment]
你可以把下面那个图截完整，我就可以看到了

**Comment by LoRexxar** [comment]
我探索了一下感觉还挺难修的...主要是vustomize-match这个模式就属于模糊匹配。

主要问题在于函数halt是二次构造的目标函数，所以这个过程没办法通过遍历ast树来完成，因为没办法确定halt会在哪里被调用。

所以发现这个函数是通过正则实现的，通过正则匹配到函数，然后才进入ast分析回溯参数，也就忽略了注释符号

**Comment by p1g3** [comment]
能否考虑把正则完善一次，判断匹配的代码前是否存在注释符这样？

LoRexxar <notifications@github.com> 于2020年12月1日周二 下午2:18写道：

**Comment by LoRexxar** [comment]
用了一个简单的方法先处理了下，观望下会不会影响到扫描

**Comment by LoRexxar** [comment]
没办法用正则来解决的，因为这不只是//的问题，还有多行注释等
