### ISSUE TITLE
命令行模式和console模式结果不一样

### ISSUE THREAD

**Issue by akkuman** [LoRexxar/Kunlun-M#126]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`Linux muniufile 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`||
|Python|`Python 3.6.9`||
|Cobra|`v2.1`||

### Description

一份源码包，采用命令行 `python kunlun.py -t source` 和采用console模式结果不一样，采用console模式会有检测结果，命令行就没有，源码包在上面上传

[CatfishBlog3.4.18.zip](https://github.com/LoRexxar/Kunlun-M/files/5819623/CatfishBlog3.4.18.zip)

**Comment by LoRexxar** [comment]
我试试看，最好有结果的截图给我看看

**Comment by akkuman** [comment]
![image](https://user-images.githubusercontent.com/7813511/104863479-fbc2f800-5970-11eb-88f1-e673eb4d7b8f.png)
![image](https://user-images.githubusercontent.com/7813511/104863770-f87c3c00-5971-11eb-880c-7e5f8f781bb5.png)

上面的是命令行，下面的是采用console直接run的

**Comment by LoRexxar** [comment]
你截图的这部分不是结果呀，这是new evil func，这个条数不一样是因为分类方式，直接命令行扫描的就会归类到一起

**Comment by akkuman** [comment]
```
 [01:44:51] [EXPORT] No filename given, save into default path(result/).
 [01:44:51] [EXPORT] Scan result exported successfully: /home/akkuman/tool/Kunlun-M/result/sources.csv
```

```
 [09:41:35] [EXPORT] No filename given, save into default path(result/).
 [09:41:35] [EXPORT] Not found vulnerability, break export...
```

这部分的结果

**Comment by LoRexxar** [comment]
我其实意思就是想看具体是什么区别，不过没事，我自己跑下

**Comment by akkuman** [comment]
输出太多了，贴不上来😂

**Comment by akkuman** [comment]
我找到问题了，我提个pr

**Comment by LoRexxar** [comment]
好的，感谢
