### ISSUE TITLE
运行在 docker 环境下出现的问题 Inappropriate ioctl for device

### ISSUE THREAD

**Issue by akkuman** [LoRexxar/Kunlun-M#131]
调用os.get_terminal_size()会出错

![image](https://user-images.githubusercontent.com/7813511/105951550-303e5e80-60ab-11eb-8d5c-e3a40cc22685.png)

**Comment by LoRexxar** [comment]
我想想，要不要把这个去掉

**Comment by akkuman** [comment]
我已经修复了，我待会提个pr
