### ISSUE TITLE
如何删除扫描结果。

### ISSUE THREAD

**Issue by yumumumu** [LoRexxar/Kunlun-M#154]
![image](https://user-images.githubusercontent.com/47736358/125418700-38529e4e-d01a-4cc7-b792-6bb70e5cbe4e.png)
只看到可以在扫描结果中删除某一条发现的问题 
如何删除整个扫描结果。应该在root模式下还是在result模式下？

**Comment by LoRexxar** [comment]
这里删除其实相当于把isactive设置成了否，所以不显示了。

好像还没有删除整个扫描结果的逻辑，需要去数据库删

**Comment by yumumumu** [comment]
感谢您  希望后期版本能加上删除扫描结果选项。毕竟去数据库删除比较麻烦

**Comment by LoRexxar** [comment]
如果要删除整个扫描结果，可以不进入这个项目啊，毕竟都要删除整个了，还不如不看。

**Comment by yumumumu** [comment]
对 我的意思就是旨在这个项目看到删除命令 在root下没删除的命令
