### ISSUE TITLE
Web只能127.0.0.1访问，配置修改无效

### ISSUE THREAD

**Issue by xj84684** [LoRexxar/Kunlun-M#191]
在settings.py中修改REMOTE_URL =“”，启动web还是127.0.0.1。

**Comment by LoRexxar** [comment]
配置文件里的REMOTE_URL不是设置启动web的ip的。

启动web的ip是-p设置的

**Comment by LoRexxar** [comment]
很抱歉这部分没有文档，有机会的话我会把配置文件里的文档补一补

**Comment by xj84684** [comment]
感谢，这部分问题我自已经自行解决了。

解决方式：

vim /usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py 

将default_addr = '127.0.0.1'  修改成 default_addr = '0.0.0.0.0' 

ps：我这里安装的是python3.8，所以文件在python3.8文件夹下，其他python版本自行修改路径
