### ISSUE TITLE
python3.9兼容问题

### ISSUE THREAD

**Issue by soapffz** [LoRexxar/Kunlun-M#204]
如图

![image](https://user-images.githubusercontent.com/43143519/139532398-ae468185-cffb-4a13-87bf-d8769d1c7e27.png)

用了2.6.2 版本 一样的问题，建议增加相关编码处理逻辑

**Comment by LoRexxar** [comment]
又是python3.9....这个毒瘤版本真的...

**Comment by LoRexxar** [comment]
我后面想办法把3.9的适配做一下吧，这个版本的语法改动太多了，不好做兼容

**Comment by soapffz** [comment]
嗯嗯 大佬辛苦了
