### ISSUE TITLE
用的是inight1997/kunlun-mirror的镜像，输出结果报错了。

### ISSUE THREAD

**Issue by Chinakentgao** [LoRexxar/Kunlun-M#206]
[08:31:35] [Console] Traceback (most recent call last):
  File "/root/Kunlun-M/core/console.py", line 189, in start                                                                                                                                                       
    command_handler(args)                                                                                                                                                                                         
  File "/root/Kunlun-M/core/console.py", line 1431, in command_run                                                                                                                                                
    cli.start(self.scan_options['target'], self.scan_options['format'], self.scan_options['output'],                                                                                                              
  File "/root/Kunlun-M/core/cli.py", line 198, in start                                                                                                                                                           
    scan(target_directory=target_directory, a_sid=a_sid, s_sid=s_sid, special_rules=pa.special_rules,                                                                                                             
  File "/root/Kunlun-M/core/engine.py", line 284, in scan                                                                                                                                                         
    show_context(c[2], c[3])                                                                                                                                                                                      
  File "/root/Kunlun-M/utils/utils.py", line 708, in show_context                                                                                                                                                 
    line_start = int(line_number) - show_line

**Comment by Chinakentgao** [comment]
之前几个代码审计都能出结果今天换了个系统的就不行。操作都是按照给的流程走的

**Comment by LoRexxar** [comment]
你这个镜像是哪里的呢，好像不是我提供的呀。

你这个bug我应该是修复了的

**Comment by Chinakentgao** [comment]
吃惊 之前用仓库的镜像下不了 才去搜了下同名的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月24日(星期三) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LoRexxar/Kunlun-M] 用的是inight1997/kunlun-mirror的镜像，输出结果报错了。 (Issue #206)





 
你这个镜像是哪里的呢，好像不是我提供的呀。
 
你这个bug我应该是修复了的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LoRexxar** [comment]
可能是镜像里没更新吧，这个bug我记得前2个版本就修了

**Comment by Chinakentgao** [comment]
好像第一次安装也是这个报错然后不知道怎么处理





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月25日(星期四) 下午4:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LoRexxar/Kunlun-M] 用的是inight1997/kunlun-mirror的镜像，输出结果报错了。 (Issue #206)





 
可能是镜像里没更新吧，这个bug我记得前2个版本就修了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LoRexxar** [comment]
也许是你运气不好...这个bug也就存在了2个小版本我记得

**Comment by Chinakentgao** [comment]
怎么解决这个问题 我镜像文件是你官网https://github.com/lazychanger/docker-kunlun-mirror 下的但是安装就报错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月25日(星期四) 下午4:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LoRexxar/Kunlun-M] 用的是inight1997/kunlun-mirror的镜像，输出结果报错了。 (Issue #206)





 
也许是你运气不好...这个bug也就存在了2个小版本我记得
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chinakentgao** [comment]
使用你https://github.com/LoRexxar/Kunlun-M的docker镜像然后进行扫描，还是没办法输出结果。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LoRexxar/Kunlun-M"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月25日(星期四) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LoRexxar/Kunlun-M] 用的是inight1997/kunlun-mirror的镜像，输出结果报错了。 (Issue #206)





 
也许是你运气不好...这个bug也就存在了2个小版本我记得
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LoRexxar** [comment]
具体命令是什么，就是console进去之后发起scan就报这个错吗

**Comment by Chinakentgao** [comment]
python3 kunlun.py scan -t ./tests/vulnerabilities/ 然后扫到最后就报错了 我怀疑是审计的系统代码问题导致扫描出现错误。然后web的启动也没办法访问我把9999端口映射出来了访问kali的一直提示连接重置然后端口也没办法通。本机都没办法访问反正问题挺多了。不知道是不是下到旧版本的镜像了。我看了下你的仓库的镜像文件跟https://github.com/lazychanger/docker-kunlun-mirror的日期也匹配不上，他是昨天更新的你这边都几个月没更新了。整了一下午没整明白







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LoRexxar/Kunlun-M"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月25日(星期四) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LoRexxar/Kunlun-M] 用的是inight1997/kunlun-mirror的镜像，输出结果报错了。 (Issue #206)





 
具体命令是什么，就是console进去之后发起scan就报这个错吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LoRexxar** [comment]
报错就这么多吗，有没有更完整的报错

**Comment by Chinakentgao** [comment]
没了只有这些报错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月25日(星期四) 晚上6:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LoRexxar/Kunlun-M] 用的是inight1997/kunlun-mirror的镜像，输出结果报错了。 (Issue #206)





 
报错就这么多吗，有没有更完整的报错
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LoRexxar** [comment]
想想办法，你这样我没法修

**Comment by Chinakentgao** [comment]
突然又正常了 不知道什么鬼。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LoRexxar/Kunlun-M"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LoRexxar/Kunlun-M] 用的是inight1997/kunlun-mirror的镜像，输出结果报错了。 (Issue #206)





 
想想办法，你这样我没法修
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LoRexxar** [comment]
下次遇到整点儿关键log
