### ISSUE TITLE
执行一半卡住

### ISSUE THREAD

**Issue by badboycxcc** [LoRexxar/Kunlun-M#223]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
kali-linux-2022-2 5.18.0-kali5-arm64.  
python 3.10.6.     
kunlun 2.6.5.     

### Description  执行卡住

<img width="1021" alt="截屏2022-09-03 下午9 17 50" src="https://user-images.githubusercontent.com/72059221/188272263-1310e87c-33fa-4bd1-974f-d8fca43aca3f.png">

**Comment by LoRexxar** [comment]
有没有-d一下，没有详细信息没法看啊

**Comment by badboycxcc** [comment]
<img width="912" alt="截屏2022-09-07 下午12 58 09" src="https://user-images.githubusercontent.com/72059221/188792193-f4241f73-a18a-43cb-b7c1-7690a9119251.png">
