### ISSUE TITLE
提问：二次注入问题

### ISSUE THREAD

**Issue by onlywant** [LoRexxar/Kunlun-M#230]
### Description

前辈您好，如果不信任来自数据库的数据的话，就是source点是来自数据库的，我应该怎么去回溯呢，想在您的代码上修改，您能赐教一下嘛

我想做一做二阶注入的问题

**Comment by LoRexxar** [comment]
没有很好的办法，kunlun-m也做不到。

因为不仅要判断source来自于数据库，还要这个数据可控要找输入点，而且数据库端的限制也没办法获取

**Comment by onlywant** [comment]
谢谢大大！我想找点其他办法获取数据端的限制，如果仅仅判断source来自数据库的话，是否不太好写，您有什么思路吗

**Comment by LoRexxar** [comment]
那只需要判断source为数据库查询函数就行了啊，只是难点根本不在这

**Comment by onlywant** [comment]
奥奥，我在调试您的代码，如果这个问题不难的话，您愿意在代码上教一下我嘛，我愿意付一些报酬

**Comment by onlywant** [comment]
> 那只需要判断source为数据库查询函数就行了啊，只是难点根本不在这

我也觉得难点不在这了，其他地方好难，感谢
