### ISSUE TITLE
settings.py.public

### ISSUE THREAD

**Issue by hex0wn** [LoRexxar/Kunlun-M#232]
![image](https://user-images.githubusercontent.com/8603870/230288134-847c7c45-d2c3-4aef-a834-d563db3283fd.png)
![image](https://user-images.githubusercontent.com/8603870/230288193-8c1e5af9-0521-4032-81fd-33ee14ca4868.png)
这是什么环境的配置泄漏在这里了

**Comment by LoRexxar** [comment]
你没看到public吗:>
